; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200

lib_deps = 
	; IMU BNO055
    adafruit/Adafruit BNO055@^1.6.3
    adafruit/Adafruit Unified Sensor@^1.1.14
    
    ; Sensor de color TCS34725
    adafruit/Adafruit TCS34725@^1.4.4
    
    ; Sensores ToF VL53L0X
    pololu/VL53L0X@^1.3.1
	adafruit/Adafruit_VL53L0X@^1.2.4
    
    ; Multiplexor I2C
    adafruit/Adafruit TCA9548A@^1.0.1
    
    ; Driver de servos PWM
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    
    ; Wire para I2C (ya incluida en Teensy)
    Wire

; Opciones de compilación
build_flags = 
    -D USB_SERIAL
    -D TEENSY41
    -O2
    ; Habilitar debug si es necesario
    ; -D DEBUG_MODE

; Opciones de upload
upload_protocol = teensy-gui
upload_speed = 115200
